### prometheus.yml
global:
  scrape_interval: 10s

scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
    - targets: ['Hostname1:8080','Hostname2:8080','Hostname1:9100','Hostname2:9100']